using System.Collections.Generic;

namespace Aplicatie_Meniu_Gradinita9
{
    public static class ListaMeniuri
    {
        public static List<string> MicDejun { get; } = new List<string>
        { 
            "",
            "BATON",
            "BISCUIŢI",
            "BISCUIȚI DE CASĂ",
            "CHEC",
            "BISCUIȚI DIGESTA",
            "BISCUIȚI MAIA",
            "BISCUIȚI POIENI",
            "BISCUIȚI TUC",
            "CEREALE",
            "FULGI DE PORUMB",
            "MINIPATEURI CU BRÂNZĂ",
            "OMLETĂ CU BRÂNZĂ LA CUPTOR",
            "OMLETĂ CU BRÂNZĂ ȘI ROȘII",
            "OMLETĂ LA CUPTOR",
            "PAINE CU OMLETA SI BRANZA,ARDEI",
            "PÂINE CU ALMETTE ȘI ARDEI KAPIA",
            "PÂINE CU BRÂNZĂ DULCE ȘI SMÂNTÂNĂ",
            "PÂINE CU OU , BRÂNZÂ ȘI MĂSLINE",
            "PÂINE CU PASTĂ DE BRÂNZĂ ȘI CASTRAVEȚI",
            "PÂINE CU PASTĂ DE FICAT ȘI RIDICHI",
            "PÂINE CU UNT , BRÂNZĂ TELEMEA ȘI CASTRAVETE",
            "PÂINE CU UNT , BRÂNZĂ TELEMEA ȘI ROȘIE",
            "PÂINE CU UNT , MUȘCHI FILE ȘI ARDEI KAPIA",
            "PÂINE CU UNT ȘI BRÂNZĂ TELEMEA",
            "PÂINE CU UNT ȘI CAȘCAVAL ȘI CASTRAVETE",
            "PÂINE CU UNT ȘI GEM",
            "PÂINE CU UNT ȘI GEM DE CAISE",
            "PÂINE CU UNT ȘI GEM DE GUTUI",
            "PÂINE CU UNT ȘI MIERE",
            "PÂINE CU UNT ȘI MUȘCHI FILE",
            "PÂINE CU UNT ȘI OU",
            "PÂINE CU SUNCA DE PUI,ROSIE,MASLINE",
            "PÂINE CU UNT , ȘUNCĂ DE PUI ȘI CASTRAVETE",
            "PÂINE CU UNT, CAȘCAVAL ȘI ARDEI KAPIA",
            "PÂINE CU UNT, CAȘCAVAL ,OU,ROSIE",
            "TARTINĂ CU OU,UNT ȘI MĂSLINE",
            "TARTINĂ CU OU,UNT ,BRÂNZĂ TELEMEA ȘI ARDEI KAPIA",
            "TARTINĂ CU OU,BRÂNZĂ ȘI MĂSLINE",
            "PAINE,CREMA DE BRANZA,OU,ROSIE",
            "PAINE,UNT SI DULCEATA DE FRUCTE DE PADURE",
            "DULCEATA DE FRUCTE DE PADURE",
            "TARTINA CU SUNCA PUI, MASLINE"
        };

        public static List<string> PranzFelul1 { get; } = new List<string>
        {
            "",
            "CIORBĂ ȚĂRĂNEASCĂ DE PUI CU FIDEA",
            "CIORBĂ DE CARTOFI",
            "CIORBĂ DE CHIMEN",
            "CIORBĂ DE CONOPIDĂ",
            "CIORBĂ DE CURCAN",
            "CIORBĂ DE FASOLE BOABE",
            "CIORBĂ DE FASOLE VERDE",
            "CIORBĂ DE LEGUME CU PASTE",
            "CIORBĂ DE LEGUME CU ZDRENȚE DE OU",
            "CIORBĂ DE LEGUME DREASĂ CU OU",
            "CIORBĂ DE PERIȘOARE",
            "CIORBĂ DE PUI A LA GREC",
            "CIORBĂ DE SALATĂ",
            "CIORBĂ DE VARZĂ",
            "CIORBĂ DE VĂCUȚĂ",
            "CIORBĂ RĂDĂUȚEANĂ",
            "CIORBĂ ȚĂRĂNEASCĂ DE CURCAN",
            "CIORBĂ ȚĂRĂNESCĂ DREASĂ CU OU",
            "CIORBIȚĂ DE LEGUME CU TĂIȚEI DE CASĂ",
            "CIORBIȚĂ DE PERIȘOARE",
            "CIORBA CU CARNE DE PORC",
            "CIORBIȚĂ DE PUI",
            "MĂMĂLIGĂ CU BRÂNZĂ ȘI SMÂNTÂNĂ",
            "MĂMĂLIGĂ ÎN STRATURI",
            "PÂINE CU ALMETTE",
            "SUPĂ CREMĂ DE BROCOLI",
            "SUPĂ CREMĂ DE DOVLEAC",
            "SUPĂ CREMĂ DE DOVLECEI",
            "SUPĂ CREMĂ DE LEGUME CU CRUTOANE",
            "SUPĂ CREMĂ DE LINTE CU CRUTOANE",
            "SUPĂ CREMĂ DE MORCOVI",
            "SUPĂ DE CURCAN",
            "SUPĂ DE FASOLE BOABE",
            "SUPĂ DE LEGUME CU GĂLUȘTE",
            "SUPĂ DE LEGUME CU PASTE ALFABET",
            "SUPĂ DE LEGUME CU TĂIȚEI DE CASĂ",
            "SUPĂ DE LEGUME CU TURNĂȚEI",
            "SUPĂ DE PUI CU GĂLUȘTE",
            "SUPĂ DE PUI CU TĂIȚEI DE CASĂ",
            "SUPĂ DE PUI CU TURNĂȚEI",
            "SUPĂ DE ROȘII CU OREZ",
            "SUPĂ DE ROȘII CU PASTE ALFABET",
            "SUPĂ DE SPANAC CU JUMERI DE OU",
            "SUPĂ DE SPANAC CU OREZ"
        };

        public static List<string> PranzFelul2 { get; } = new List<string>
        {
            "",
            "ARDEI UMPLUT",
            "BUDINCĂ CU BRÂNZĂ LA CUPTOR",
            "BUDINCĂ DE CARTOFI",
            "BUDINCĂ DE OREZ CU PIEPT DE PUI",
            "CARTOFI GRATINAȚI LA CUPTOR",
            "CHIFTELUȚE CU PASTE ÎN SOS ROȘU",
            "CHIFTELUȚE MARINATE",
            "CUȘ CUȘ CU CARNE DE CURCAN",
            "FICĂȚEI DE PUI CU PIURE DE CARTOFI",
            "FRIPTURĂ DE CURCAN CU GARNITURĂ DE LEGUME",
            "FRIPTURĂ DE CURCAN LA CUPTOR CU CARTOFI ȚĂRĂNEȘTI",
            "GHIVECI DE LEGUME",
            "GHIVECI DE LEGUME CU CARNE DE CURCAN",
            "GHIVECI DE LEGUME CU CARNE DE PUI",
            "GUJOANE DE PUI CU PIURE DE CARTOFI",
            "IAHNIE DE FASOLE CU CARNE",
            "LASAGNA",
            "MĂMĂLIGĂ CU BRÂNZĂ DE VACI ȘI IAURT",
            "MĂMĂLIGĂ CU TOCĂNIȚĂ DE CARNE",
            "MÂNCARE DE FASOLE VERDE CU PULPE DE PUI",
            "MÂNCARE DE SPANAC CU PIEPT DE PUI",
            "MÂNCARICA DE PĂSTĂI CU CARNE DE CURCAN",
            "MÂNCĂRICĂ DE MAZĂRE CU CARNE DE CURCAN",
            "MÂNCĂRICĂ DE MAZĂRE CU CARNE DE PUI",
            "MÂNCĂRICĂ DE MAZĂRE CU CARNE DE VITĂ",
            "MUSACA DE CARTOFI",
            "OSTROPEL DE PUI",
            "OSTROPEL DE PUI CU GARNITURĂ DE CARTOFI NATUR",
            "PASTE BOLOGNEZE",
            "PASTE CU BRÂNZĂ",
            "PÂINE CU UNT,MUȘCHI FILE ȘI ROȘIE CHERRY",
            "MANCARE DE ROSII CU INIMI SI PIPOTE",
            "PIEPT DE PUI LA GRĂTAR CU CARTOFI NATUR",
            "PIEPT DE PUI LA GRĂTAR CU CARTOFI ȚĂRĂNEȘTI",
            "PIEPT DE PUI LA GRĂTAR CU GARNITURĂ DE OREZ",
            "PIEPT DE PUI LA GRĂTAR CU LEGUME LA CUPTOR",
            "PIEPT DE PUI LA GRĂTAR CU LEGUME MEXICANE",
            "PIEPT DE PUI LA GRĂTAR CU PIURE DE CARTOFI",
            "PILAF CU CARNE DE PUI",
            "PILAF CU CIUPERCI",
            "PIURE DE CARTOFI CU CARNE DE PORC LA CUPTOR",
            "PIURE DE MORCOVI CU PULPE DE PUI LA CUPTOR",
            "PULPE DE PUI CU LEGUME LA CUPTOR",
            "PULPE DE PUI CU SPANAC ȘI OREZ",
            "PULPE DE PUI LA CUPTOR CU CARTOFI NATUR",
            "PULPE DE PUI LA CUPTOR CU CUS-CUS",
            "PULPE DE PUI LA CUPTOR CU GARNITURĂ DE OREZ",
            "PULPE DE PUI LA CUPTOR CU LEGUME MEXICANE",
            "PULPE DE PUI LA CUPTOR CU PIURE DE CARTOFI",
            "PULPE DE PUI LA CUPTORCU SOTE DE BROCOLI ȘI MORCOVI BABY",
            "RIZZOTTO CU CARNE DE CURCAN",
            "SOTE DE FASOLE VERDE CU FRIPTURĂ DE PUI LA CUPTOR",
            "SPAGETE CU CARNE DE CURCAN ÎN SOS ROȘU",
            "SUFLEU DE CARTOFI CU MUȘCHI FILE ȘI CAȘCAVAL",
            "TOCĂNIȚĂ DE CARTOFI CU PULPE DE PUI",
            "TOCĂNIȚĂ DE CEAPĂ CU CARNE DE PORC",
            "TOCĂNIȚĂ DE CEAPĂ CU CARNE DE PUI",
            "TOCĂNIȚĂ DE LEGUME CU CARNE DE PUI",
            "TOCHITURĂ DE PUI ȘI FICĂȚEI",
            "MAMALIGA",
            "LEGUME MEXICANE CU PUI",
            "PIURE DE CARTOFI CU CARNE DE PUI",
            "VARZA A LA CLUJ",
            "PILAF CU CARNE DE CURCAN",
            "BUDINCA DE MACAROANE"
        };

        public static List<string> Gustare { get; } = new List<string>
        {
            "",
            "ACTIMEL",
            "BATON NESQUIK",
            "BISCUIȚI BELVITA",
            "BISCUIȚI DIGESTA",
            "BISCUIȚI LEIBNIZ",
            "BISCUIȚI MAIA",
            "BISCUIȚI POIENI",
            "BISCUIȚI TEDI",
            "BISCUIȚI TUC",
            "BANANA",
            "BRIOȘĂ",
            "CEREALE CU LAPTE",
            "CHEC CU CACAO",
            "CHEC CU LAPTE",
            "CORN CU VANILIE",
            "COVRIGEI ALKA",
            "COVRIGEI VANILAȚI",
            "COVRIGI DULCI",
            "COZONAC",
            "CRACKERS CU SUSAN",
            "CROISSANT CU CIOCOLATĂ",
            "CROISSANT CU VIȘINE",
            "EUGENIA",
            "FAGURE CU CIOCOLATĂ",
            "GOGOAȘĂ SIMPLĂ",
            "GOLDFISHILI(STICKS)",
            "KINDER BUENO(43g)",
            "KINDER COUNTRY",
            "MAR",
            "NECTARINA",
            "PÂINE CU UNT CAȘCAVAL ȘI CEAI",
            "PLĂCINTĂ CU BRÂNZĂ",
            "PLĂCINTĂ CU DOVLEAC",
            "PLĂCINTĂ CU MERE",
            "PARA",
            "PRĂJITURA MĂGURA",
            "PRĂJITURICĂ BARNIE",
            "PREAMBALATĂ",
            "PRICOMIGDALĂ",
            "SALAM DE BISCUIȚI",
            "ȘTRUDEL CU MERE",
            "ȘTRUDEL CU VIȘINE",
            "TRIGON CU BRÂNZĂ ȘI CAȘCAVAL",
            "IAURT",
            "PORTOCALA"
        };
    }
}
